function form(){
    console.log(document.getElementById("codigo").value)
    console.log(document.getElementById("avaliar").checked)
    console.log(document.getElementById("tipo").event.target.value)
    console.log(document.getElementById("pendFinanc").checked)
    console.log(document.getElementById("meses_atrado").value)
    console.log(document.getElementById("contrato_atv").checked)
    console.log(document.getElementById("nome").value)
    console.log(document.getElementById("cnpj").value)
    console.log(document.getElementById("cpf").value)
    console.log(document.getElementById("telefone").value)
    console.log(document.getElementById("celular").value)
    console.log(document.getElementById("contato").value)
    console.log(document.getElementById("ramoAtv").value)
    console.log(document.getElementById("cidade").value)
    console.log(document.getElementById("rua").value)
    console.log(document.getElementById("bairro").value)
    console.log(document.getElementById("numero").value)
    console.log(document.getElementById("UF").value)
    console.log(document.getElementById("cep").value)
    console.log(document.getElementById("complemento").value)
    console.log(document.getElementById("ip_acesso").value)
    console.log(document.getElementById("obv").value)
    console.log(document.getElementById("ativo").checked)
    console.log(document.getElementById("sistema").value)
    console.log(document.getElementById("valor").value)
    console.log(document.getElementById("data_inicio").value)
    console.log(document.getElementById("data_fim").value)
}

export default form
